Models/Base.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Pokedex5.Models
{
    public class Base
    {
        [Range(1, 255)]
        public int Attack { get; set; }
        [Range(1, 255)]
        public int Defense { get; set; }
        [Range(1, 255)]
        public int Hp { get; set; }
        [Range(1, 255)]
        public int SpAttack { get; set; }
        [Range(1, 255)]
        public int SpDefense { get; set; }
        [Range(1, 255)]
        public int Speed { get; set; }
    }
}

Models/IPokedex.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Pokedex5.Models
{
    public interface IPokedex
    {
        Pokemon Get(int id);
        List<Pokemon> GetAll();
        public DateTime GeneratedAt { get; set; }
        void Save(Pokemon pokemon);
    }
}

Models/JsonPokedex.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace Pokedex5.Models
{
    public class JsonPokedex : IPokedex
    {
        private List<Pokemon> pokemons;

        public DateTime GeneratedAt { get; set; }

        private List<Pokemon> getPokemon()
        {
            var options = new JsonSerializerOptions
            {
                PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
                WriteIndented = true
            };
            var lines = System.IO.File.ReadAllText(@"pokedex.json");
            return JsonSerializer.Deserialize<List<Pokemon>>(lines, options);
        }

        public JsonPokedex()
        {
            this.pokemons = getPokemon();
            this.GeneratedAt = DateTime.Now;
        }

        public Pokemon Get(int id)
        {
            foreach (Pokemon p in pokemons)
            {
                if (p.Id == id)
                {
                    return p;
                }
            }
            return null;
        }

        public List<Pokemon> GetAll()
        {
            return pokemons;
        }

        public void Save(Pokemon pokemon)
        {
            var index = this.pokemons.FindIndex(p => p.Id == pokemon.Id);
            this.pokemons[index] = pokemon;
        }
    }
}

Models/Name.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Pokedex5.Models
{
    public class Name
    {
        public string Chinese { get; set; }
        public string English { get; set; }
        public string French { get; set; }
        public string Japanese { get; set; }
    }
}

Models/Pokemon.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Pokedex5.Models
{
    public class Pokemon
    {
        public Base Base { get; set; }
        public int Id { get; set; }
        public Name Name { get; set; }
        public string[] Type { get; set; }
    }
}

ViewModels/PokedexListViewModel.cs
using Pokedex5.Controllers;
using Pokedex5.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Pokedex5.ViewModels
{
    public class PokedexListViewModel
    {
        public string PageGenerated { get; set; }
        public IEnumerable<Pokemon> Pokemons { get; set; }
        public SortField SortField { get; set; }
        public SortDirection SortDirection { get; set; }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Pokedex5.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

    }
}

Controllers/PokedexController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Pokedex5.Models;
using Pokedex5.ViewModels;

namespace Pokedex5.Controllers
{
    public enum SortField
    {
        Id, Name, Type
    }

    public enum SortDirection
    {
        ASC, DESC
    }
    public class PokedexController : Controller
    {
        private IPokedex pokedex;
        private IConfiguration configuration;
        private ILogger<PokedexController> logger;
        public PokedexController(IConfiguration configuration, ILogger<PokedexController> logger, IPokedex pokedex)
        {
            this.configuration = configuration;
            this.logger = logger;
            this.pokedex = pokedex;
        }
        
        public IActionResult Index([FromQuery] SortField sort = SortField.Id, [FromQuery] SortDirection sortDirection = SortDirection.ASC)
        {
            logger.LogInformation("A user has used the pokedex");
            IEnumerable<Pokemon> pokemons = pokedex.GetAll();
            switch (sort)
            {
                case SortField.Id:
                    pokemons = (sortDirection == SortDirection.ASC) ? pokemons.OrderBy(p => p.Id) : pokemons.OrderByDescending(p => p.Id);
                    break;
                case SortField.Name:
                    pokemons = (sortDirection == SortDirection.ASC) ? pokemons.OrderBy(p => p.Name.English) : pokemons.OrderByDescending(p => p.Name.English);
                    break;
                case SortField.Type:
                    pokemons = (sortDirection == SortDirection.ASC) ? pokemons.OrderBy(p => p.Type[0]) : pokemons.OrderByDescending(p => p.Type[0]);
                    break;
            }
            PokedexListViewModel pokedexListViewModel = new PokedexListViewModel
            {
                PageGenerated = pokedex.GeneratedAt.ToString(),
                Pokemons = pokemons,
                SortField = sort,
                SortDirection = sortDirection
            };

            return View(pokedexListViewModel);
        }

        public IActionResult Details(int id)
        {
            Pokemon pokemon = pokedex.Get(id);
            if (pokemon != null)
            {
                return View(pokemon);
            }
            return NotFound();
        }
        [HttpPost]
        public IActionResult Details(int id, Pokemon pokemon)
        {
            Pokemon p = pokedex.Get(id);
            
            if (ModelState.IsValid)
            {
                p.Base = pokemon.Base;
                TempData["Message"] = $"{p.Name.English} was updated!";
                this.pokedex.Save(p);
            }
            return View(p);
        }
    }
}

Views/Home/Index.cshtml
@{ 
    ViewBag.Title = "Home";
}
<h1>Welcome</h1>
<p>Welcome to the Pokedex web application. Feel free to look around and play with the pokemon.</p>

Views/Pokedex/Details.cshtml
@model Pokedex5.Models.Pokemon
@{
    ViewBag.Title = $"{Model.Name.English}";
}
@if (TempData["Message"] != null)
{
    <div class="alert alert-success" role="alert">
        @TempData["Message"]
    </div>
}
<form method="post" asp-controller="Pokedex" asp-Action="Details">
    <table class="table">
        <tr>
            <th>Image</th>
            <td><img src="~/Images/@(Model.Id).png" /></td>
        </tr>
        <tr>
            <th scope="row">Name</th>
            <td>@Model.Name.English</td>
        </tr>
        <tr>
            <th scope="row">Types</th>
            <td>
                <ul>
                    @foreach (var type in Model.Type)
                    {
                        <li>@type</li>
                    }
                </ul>
            </td>
        </tr>
        <tr>
            <th scope="row">Hp</th>
            <td>
                <input asp-for="Base.Hp" />
                <div class="invalid-feedback" style="display:block;">
                    <span asp-validation-for="Base.Hp"></span>
                </div>
            </td>
        </tr>
        <tr>
            <th scope="row">Attack</th>
            <td>
                <input asp-for="Base.Attack" />
                <div class="invalid-feedback" style="display:block;">
                    <span asp-validation-for="Base.Attack"></span>
                </div>
            </td>
        </tr>
        <tr>
            <th scope="row">Defense</th>
            <td>
                <input asp-for="Base.Defense" />
                <div class="invalid-feedback" style="display:block;">
                    <span asp-validation-for="Base.Defense"></span>
                </div>
            </td>
        </tr>
        <tr>
            <th scope="row">Speed</th>
            <td>
                <input asp-for="Base.Speed" />
                <div class="invalid-feedback" style="display:block;">
                    <span asp-validation-for="Base.Speed"></span>
                </div>
            </td>
        </tr>
        <tr>
            <th scope="row">Sp. Attack</th>
            <td>
                <input asp-for="Base.SpAttack" />
                <div class="invalid-feedback" style="display:block;">
                    <span asp-validation-for="Base.SpAttack"></span>
                </div>
            </td>
        </tr>
        <tr>
            <th scope="row">Sp. Defense</th>
            <td>
                <input asp-for="Base.SpDefense" />
                <div class="invalid-feedback" style="display:block;">
                    <span asp-validation-for="Base.SpDefense"></span>
                </div>
            </td>
        </tr>
    </table>
    <button type="submit">Save</button>
</form>

Views/Pokedex/Index.cshtml
@model PokedexListViewModel
@{
    ViewBag.Title = "Pokedex";
    int MaxPokemon = int.Parse(Configuration["MaxPokemon"]);
}
<h1>Pokedex</h1>
@{
    int i = 0;
}
<div class="btn-group" role="group" aria-label="Sort">
    <a asp-action="Index" asp-route-sort="Id" asp-route-sortDirection="@Model.SortDirection" class="btn btn-secondary @(Model.SortField == Pokedex5.Controllers.SortField.Id?"active":"")">Id</a>
    <a asp-action="Index" asp-route-sort="Name" asp-route-sortDirection="@Model.SortDirection" class="btn btn-secondary @(Model.SortField == Pokedex5.Controllers.SortField.Name?"active":"")">Name</a>
    <a asp-action="Index" asp-route-sort="Type" asp-route-sortDirection="@Model.SortDirection" class="btn btn-secondary @(Model.SortField == Pokedex5.Controllers.SortField.Type?"active":"")">Type</a>
</div>
<div class="btn-group" role="group" aria-label="Sort direction">
    <a asp-action="Index" asp-route-sort="@Model.SortField" asp-route-sortDirection="ASC" class="btn btn-secondary @(Model.SortDirection == Pokedex5.Controllers.SortDirection.ASC?"active":"")">Ascending</a>
    <a asp-action="Index" asp-route-sort="@Model.SortField" asp-route-sortDirection="DESC" class="btn btn-secondary @(Model.SortDirection == Pokedex5.Controllers.SortDirection.DESC?"active":"")">Descending</a>
</div>
<p></p>
@foreach (Pokemon p in Model.Pokemons)
{
    var url = $"/Images/{p.Id}.png";
    <a asp-controller="Pokedex" asp-action="Details" asp-route-id="@p.Id"> <img src="@url" /></a>
    if (i++ > MaxPokemon)
    {
        break;
    }
}
<br />
<b>Page generated: @Model.PageGenerated</b>

Views/Shared/_Layout.cshtml
@functions{
    bool isDarkMode(string color)
    {
        System.Drawing.Color col = System.Drawing.ColorTranslator.FromHtml(color);
        if (col.R * 0.2126 + col.G * 0.7152 + col.B * 0.0722 > 255 / 2)
        {
            return false;
        }
        else
        {
            return true;
        }
    }
}
@{ 
    var NavBarColor = Configuration["NavBarColor"];
}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Pokemon - @ViewBag.Title</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-@(isDarkMode(NavBarColor) ? "dark": "light")" style="background-color: @NavBarColor">
        <a class="navbar-brand" href="#">
            @{
                Random rnd = new Random();
                int pokemon = rnd.Next(0, 151);
                var url = $"/Images/{pokemon}.png";
            }
            <img src="@url" width="30" height="30" alt="" loading="lazy">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Home" asp-action="Index">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Pokedex" asp-action="Index">Pokedex</a>
                </li>
            </ul>
        </div>
    </nav>
    @RenderBody()
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

</body>
</html>